### ISSUE TITLE
No result from suggested case

### ISSUE THREAD

**Issue by abrudz** [abrudz/tacit.help#12]
[The source](https://github.com/awagga/tacit.help/blob/master/explicit.aplf#L33) suggests using tacit.help if confused about `'}',⍨'{',⊢(/⍨)∨∘⌽⍨⍤⍷⍨⍲∊∘'()'` but [this fails](https://tacit.help/?f=%27%7B%27%2C%E2%8D%A8%27%7D%27%2C%E2%8A%A2(%2F%E2%8D%A8)%E2%88%A8%E2%88%98%E2%8C%BD%E2%8D%A8%E2%8D%A4%E2%8D%B7%E2%8D%A8%E2%8D%B2%E2%88%8A%E2%88%98%27()%27&g=#). Replacing the curly brace literals with e.g. square brackets [works](https://tacit.help/?f=%27%5B%27%2C%E2%8D%A8%27%5D%27%2C%E2%8A%A2(%2F%E2%8D%A8)%E2%88%A8%E2%88%98%E2%8C%BD%E2%8D%A8%E2%8D%A4%E2%8D%B7%E2%8D%A8%E2%8D%B2%E2%88%8A%E2%88%98%27()%27&g=).

**Comment by ghost** [comment]
https://github.com/awagga/tacit.help/commit/85d606ede5e168be9fbe05c6c10fff95054d7cb7
