### ISSUE TITLE
Assignments within quotes are still erased

### ISSUE THREAD

**Issue by ghost** [abrudz/tacit.help#13]
https://tacit.help/?f=%27f%E2%86%90%27%2Cf#

Offending line is: 
```
_ ← '[A-Za-z](?=(\s*)←)' ⎕S {⎕EX 'ns.',⍵.Match}⊢train
```

**Comment by abrudz** [comment]
[Same goes for comments](https://tacit.help/?f=%27f%E2%86%90%27%2Cf#).

I believe the fix is simple:
```apl
_ ← '[A-Za-z](?=(\s*)←)' ⎕S {⎕EX 'ns.',⍵.Match}'''[^'']*''|⍝.*'⎕R''⊢train
```
