### ISSUE TITLE
Incorrect   SYNTAX ERROR: Unpaired parenthesis

### ISSUE THREAD

**Issue by zfac030** [abrudz/tacit.help#15]
Get "SYNTAX ERROR: Unpaired parenthesis" for (⊣g⍨∘⊢f)h(g⍛(⊢f))

**Comment by ghost** [comment]
[doesn't seem to error for me](https://tacit.help/?f=(%E2%8A%A3g%E2%8D%A8%E2%88%98%E2%8A%A2f)h(g%E2%8D%9B(%E2%8A%A2f))#)

**Comment by zfac030** [comment]
huh - weird, definitely did when I arrived at that expression.

Lets close this then as seems sorted.
