### ISSUE TITLE
Commute incorrectly converted

### ISSUE THREAD

**Issue by bear8642** [abrudz/tacit.help#21]
(⍉¯1∘↓⍪⊖)⍣2⊢∘.⌊⍨⍳ → {({⍉((¯1↓⍵)⍪(⊖⍵))}⍣2)((⍳⍵)(∘.⌊)⍵)}
not the expected {({⍉((¯1↓⍵)⍪(⊖⍵))}⍣2)((⍳⍵)(∘.⌊)⍳⍵)}

https://tacit.help/?f=(%E2%8D%89%C2%AF1%E2%88%98%E2%86%93%E2%8D%AA%E2%8A%96)%E2%8D%A32%E2%8A%A2%E2%88%98.%E2%8C%8A%E2%8D%A8%E2%8D%B3

**Comment by abrudz** [comment]
Closing this as

**Comment by abrudz** [comment]
There's no bug here: `⊢∘.⌊⍨⍳` is `⍳∘.⌊⊢` which expands to `(⍳⍵)(∘.⌊)⍵`
