### ISSUE TITLE
Select glyph (⊇) not supported

### ISSUE THREAD

**Issue by bear8642** [abrudz/tacit.help#23]
The glyph for [Select ](https://aplwiki.com/wiki/From)(⊇) isn't supported, whilst [Reverse Compose](https://aplwiki.com/wiki/Reverse_Compose) (⍛) is preventing ⍋⍛⊇ from being explored.

**Comment by abrudz** [comment]
As opposed to `⍛`, the design for `⊇` is not finalised, and it isn't included in Dyalog 20.0.
